# this is still a placeholder
services:
    wp-united:
	    class: phpbb_ext_wp-united_main
	    arguments: 
		    - %core_root_path%
			- @user
			- @config
			- @template
			- @dbal.conn
		tags:
		    { name: wp-united.main }
